// Conteudo do simulado adaptado. Texto dos poemas mantido integralmente.
// b: true marca a palavra-alvo em negrito (apoio de localizacao visual).

const PARTES = [
  {
    n: 1,
    titulo: "Chuva na cidade",
    imagem: "Chuva caindo na diagonal sobre o telhado de uma casa. No chão molhado, poças com ondas circulares.",
    versos: [
      "Cai a chuva na cidade,",
      "tamborila no telhado,",
      "e a rua, toda encharcada,",
      "vira um rio prateado.",
      "",
      "A chuva bate na vidraça:",
      "tec, tec, tec — pede passagem.",
      "O vento, que veio com ela,",
      "sacode as folhas da paisagem.",
      "",
      "Depois, cansada de tanto,",
      "a chuva senta no chão,",
      "e a cidade, sem seu manto,",
      "respira de mansidão.",
    ],
    perguntas: [
      {
        n: 1,
        pista: "Leia os versos 2 e 10.",
        imagem: "Dois quadros lado a lado. À esquerda, a chuva batendo no telhado como quem toca tambor. À direita, a chuva sentada no chão molhado, descansando. Etiquetas: “verso 2 — tamborila no telhado” e “verso 10 — senta no chão”.",
        enunciado: [
          [{ t: "No poema, a chuva " }, { t: "tamborila", b: 1 }, { t: " e " }, { t: "senta no chão", b: 1 }, { t: "." }],
          [{ t: "Tamborilar e sentar são ações de gente." }],
          [{ t: "Como se chama esse recurso?" }],
        ],
        alt: ["Comparação.", "Personificação.", "Hipérbole."],
        certa: "B",
        desc: "D043_P",
        hab: "Reconhecer recursos estilísticos na construção do texto.",
      },
      {
        n: 2,
        pista: "Leia o verso 6.",
        imagem: "A vidraça de uma janela com a chuva batendo. Saindo do vidro, as letras “tec, tec, tec” com marquinhas de impacto. Etiqueta: “verso 6”.",
        enunciado: [
          [{ t: "No verso “tec, tec, tec — pede passagem”, a palavra " }, { t: "tec", b: 1 }, { t: " foi usada para:" }],
        ],
        alt: ["Criar uma rima.", "Imitar o som da chuva na vidraça.", "Mostrar que o poema acabou."],
        certa: "B",
        desc: "D043_P",
        hab: "Reconhecer recursos estilísticos na construção do texto.",
      },
      {
        n: 3,
        pista: "Leia os versos 3 e 4.",
        imagem: "A rua depois da chuva: água por toda parte, poças fundas, calçada escura de tanta água. Etiqueta: “verso 3 — a rua, toda encharcada”.",
        enunciado: [
          [{ t: "A rua estava " }, { t: "encharcada", b: 1 }, { t: "." }],
          [{ t: "Isso quer dizer que a rua estava:" }],
        ],
        alt: ["Mal iluminada.", "Muito molhada.", "Muito estreita."],
        certa: "B",
        desc: "D022_P",
        hab: "Inferir o sentido de palavra ou expressão pelo contexto.",
      },
    ],
  },
  {
    n: 2,
    titulo: "O velho relógio da sala",
    imagem: "Um relógio antigo de parede, com pêndulo, ponteiros e as marcações das horas, numa sala com piso de madeira.",
    versos: [
      "Na parede da sala antiga",
      "o relógio fala sozinho.",
      "Ninguém escuta o que ele diga —",
      "tic-tac, tic-tac, no seu cantinho.",
      "",
      "Ele não dorme, não descansa,",
      "não perde a hora, não se cala:",
      "guarda o passo de cada lembrança",
      "que atravessa de leve a sala.",
      "",
      "Quando a casa fica vazia",
      "e a noite se estica devagar,",
      "o relógio, com teimosia,",
      "não se cansa de contar.",
    ],
    perguntas: [
      {
        n: 4,
        pista: "Leia o verso 4.",
        imagem: "O relógio com o pêndulo balançando de um lado para o outro. Em volta, “tic-tac” repetido várias vezes, acompanhando o movimento. Etiqueta: “verso 4 — tic-tac, tic-tac”.",
        enunciado: [
          [{ t: "O poeta repete " }, { t: "tic-tac, tic-tac", b: 1 }, { t: "." }],
          [{ t: "Ele repete para:" }],
        ],
        alt: ["Imitar o som do relógio e mostrar que o tempo não para.", "Dizer que o relógio está quebrado.", "Avisar que a casa está vazia."],
        certa: "A",
        desc: "D043_P",
        hab: "Reconhecer recursos estilísticos na construção do texto.",
      },
      {
        n: 5,
        pista: "Leia o verso 11.",
        imagem: "A sala escura e vazia, todos dormindo, e o relógio continuando a marcar as horas mesmo assim. Etiqueta: “verso 11 — com teimosia”.",
        enunciado: [
          [{ t: "O relógio conta as horas " }, { t: "com teimosia", b: 1 }, { t: "." }],
          [{ t: "A palavra " }, { t: "teimosia", b: 1 }, { t: " quer dizer:" }],
        ],
        alt: ["Tristeza.", "Insistência.", "Preguiça."],
        certa: "B",
        desc: "D022_P",
        hab: "Inferir o sentido de palavra ou expressão pelo contexto.",
      },
      {
        n: 6,
        pista: "Leia o verso 10.",
        imagem: "A noite desenhada como uma faixa comprida que vai se esticando devagar pela sala, da janela até o relógio. Etiqueta: “verso 10 — a noite se estica devagar”.",
        enunciado: [
          [{ t: "“A noite " }, { t: "se estica devagar", b: 1 }, { t: ".”" }],
          [{ t: "Essa frase quer dizer que a noite:" }],
        ],
        alt: ["Passa devagar.", "Chega mais cedo.", "Fica mais fria."],
        certa: "A",
        desc: "D022_P",
        hab: "Inferir o sentido de palavra ou expressão pelo contexto.",
      },
    ],
  },
  {
    n: 3,
    titulo: "Mar de manhã",
    imagem: "O mar ao amanhecer: linha do horizonte, faixas de ondas e o sol nascendo à direita, com espuma na areia.",
    versos: [
      "O mar amanhece manso,",
      "murmura, molha a areia,",
      "e a espuma, branca de cansaço,",
      "some como quem passeia.",
      "",
      "A onda chega sem pressa,",
      "lambe o pé de quem espera,",
      "recua e não confessa",
      "o segredo que ela era.",
      "",
      "O sol, moeda de ouro,",
      "rola devagar no azul.",
      "O dia é um barco novo",
      "apontado para o sul.",
    ],
    perguntas: [
      {
        n: 7,
        pista: "Leia os versos 1 e 2 em voz baixa.",
        imagem: "O mar de manhã com as palavras “mar, amanhece, manso, murmura, molha” escritas sobre as ondas. A letra M de cada palavra aparece maior e em outra cor. Etiqueta: “versos 1 e 2”.",
        enunciado: [
          [{ t: "Nos versos 1 e 2, o som da letra " }, { t: "M", b: 1 }, { t: " se repete muitas vezes." }],
          [{ t: "Como se chama esse recurso?" }],
        ],
        alt: ["Aliteração.", "Onomatopeia.", "Hipérbole."],
        certa: "A",
        desc: "D043_P",
        hab: "Reconhecer recursos estilísticos na construção do texto.",
      },
      {
        n: 8,
        pista: "Leia o verso 4.",
        imagem: "Dois quadros ligados pela palavra COMO escrita no meio. À esquerda, a espuma sumindo na areia. À direita, uma pessoa passeando devagar na praia. Etiqueta: “verso 4 — some como quem passeia”.",
        enunciado: [
          [{ t: "No verso “some " }, { t: "como", b: 1 }, { t: " quem passeia”, a palavra " }, { t: "como", b: 1 }, { t: " serve para:" }],
        ],
        alt: ["Comparar a espuma com uma pessoa que passeia.", "Imitar um som.", "Juntar duas ideias contrárias."],
        certa: "A",
        desc: "D043_P",
        hab: "Reconhecer recursos estilísticos na construção do texto.",
      },
      {
        n: 9,
        pista: "Leia os versos 5 e 6.",
        imagem: "Close da beira da praia: a onda chegando bem devagar e encostando de leve no pé de alguém parado na areia. Etiqueta: “verso 6 — lambe o pé de quem espera”.",
        enunciado: [
          [{ t: "A onda “" }, { t: "lambe", b: 1 }, { t: " o pé de quem espera”." }],
          [{ t: "Aqui, o verbo " }, { t: "lamber", b: 1 }, { t: " quer dizer:" }],
        ],
        alt: ["Tocar de leve.", "Morder com força.", "Empurrar para longe."],
        certa: "A",
        desc: "D022_P",
        hab: "Inferir o sentido de palavra ou expressão pelo contexto.",
      },
    ],
  },
  {
    n: 4,
    titulo: "Vento no sertão",
    imagem: "Chão rachado e ressecado, poeira levada pelo vento e uma pequena planta brotando no primeiro plano.",
    versos: [
      "O vento veio do norte",
      "com mil braços de poeira,",
      "carregou a tarde inteira",
      "e ainda pediu mais sorte.",
      "",
      "No chão estorricado",
      "a terra pede uma gota;",
      "o céu, de azul lavado,",
      "não devolve nem uma nota.",
      "",
      "Aqui é seco, é sede, é sol;",
      "ali, no verde do quintal,",
      "uma flor teima em nascer",
      "no meio de tanto sal.",
    ],
    perguntas: [
      {
        n: 10,
        pista: "Leia os versos 2 e 3.",
        imagem: "O vento desenhado como um redemoinho enorme com muitos e muitos braços feitos de poeira, ocupando o céu inteiro. Etiqueta: “verso 2 — mil braços de poeira”.",
        enunciado: [
          [{ t: "O vento tinha “" }, { t: "mil braços de poeira", b: 1 }, { t: "” e carregou “a tarde inteira”." }],
          [{ t: "O poeta exagerou de propósito." }],
          [{ t: "Como se chama esse recurso?" }],
        ],
        alt: ["Comparação.", "Hipérbole.", "Onomatopeia."],
        certa: "B",
        desc: "D043_P",
        hab: "Reconhecer recursos estilísticos na construção do texto.",
      },
      {
        n: 11,
        pista: "Leia os versos 9 e 10.",
        imagem: "Uma imagem dividida ao meio. De um lado, terra rachada, sem água. Do outro, um quintal verde com plantas. Etiquetas: “verso 9 — é seco” e “verso 10 — no verde do quintal”.",
        enunciado: [
          [{ t: "De um lado o poeta fala em " }, { t: "seco", b: 1 }, { t: ". Do outro lado, em " }, { t: "verde", b: 1 }, { t: "." }],
          [{ t: "Ele juntou duas ideias contrárias." }],
          [{ t: "Como se chama esse recurso?" }],
        ],
        alt: ["Antítese.", "Aliteração.", "Metáfora."],
        certa: "A",
        desc: "D043_P",
        hab: "Reconhecer recursos estilísticos na construção do texto.",
      },
      {
        n: 12,
        pista: "Leia os versos 5 e 6.",
        imagem: "Close do chão do sertão: terra dura, cheia de rachaduras, sol forte em cima e nenhuma água à vista. Etiqueta: “verso 5 — no chão estorricado”.",
        enunciado: [
          [{ t: "O chão estava " }, { t: "estorricado", b: 1 }, { t: " e a terra pedia uma gota de água." }],
          [{ t: "A palavra " }, { t: "estorricado", b: 1 }, { t: " quer dizer:" }],
        ],
        alt: ["Cheio de plantas.", "Muito seco.", "Molhado de chuva."],
        certa: "B",
        desc: "D022_P",
        hab: "Inferir o sentido de palavra ou expressão pelo contexto.",
      },
    ],
  },
  {
    n: 5,
    titulo: "Bicicleta velha",
    imagem: "Uma bicicleta vista de lado, descendo a ladeira, com traços de movimento atrás das rodas.",
    versos: [
      "Minha bicicleta velha",
      "tem a corrente enferrujada,",
      "o guidão que sempre entorta",
      "e a campainha estourada.",
      "",
      "Mas quando desce a ladeira,",
      "desembestada, sem freio,",
      "ela vira uma cometa",
      "com um menino no meio.",
      "",
      "Roda, roda, roda, roda —",
      "a rua vira um borrão.",
      "O vento entra na camisa",
      "e faz vela do meu coração.",
    ],
    perguntas: [
      {
        n: 13,
        pista: "Leia o fim dos versos 1, 2, 3 e 4.",
        imagem: "A bicicleta velha desenhada com destaque para três partes, cada uma com uma setinha e o nome que aparece no poema: “corrente enferrujada”, “guidão que sempre entorta” e “campainha estourada”.",
        enunciado: [
          [{ t: "Rima é quando duas palavras terminam com o mesmo som." }],
          [{ t: "Na primeira estrofe, as palavras que rimam são:" }],
        ],
        alt: ["Velha e guidão.", "Enferrujada e estourada.", "Corrente e campainha."],
        certa: "B",
        desc: "D043_P",
        hab: "Reconhecer recursos estilísticos na construção do texto.",
      },
      {
        n: 14,
        pista: "Leia os versos 9 e 10.",
        imagem: "A bicicleta descendo muito rápido. Ela aparece nítida, e a rua atrás dela aparece toda embaçada, virada em riscos. Etiqueta: “verso 10 — a rua vira um borrão”.",
        enunciado: [
          [{ t: "A bicicleta desce rápido e “a rua vira um " }, { t: "borrão", b: 1 }, { t: "”." }],
          [{ t: "Essa frase quer dizer que:" }],
        ],
        alt: ["A rua está suja de tinta.", "A bicicleta passa tão rápido que tudo fica embaçado.", "A rua está cheia de buracos."],
        certa: "B",
        desc: "D022_P",
        hab: "Inferir o sentido de palavra ou expressão pelo contexto.",
      },
      {
        n: 15,
        pista: "Leia os versos 5 e 6.",
        imagem: "A bicicleta disparando ladeira abaixo, com o menino segurando firme, cabelo para trás e os pés fora dos pedais. Etiqueta: “verso 6 — desembestada, sem freio”.",
        enunciado: [
          [{ t: "A bicicleta desce a ladeira “" }, { t: "desembestada", b: 1 }, { t: ", sem freio”." }],
          [{ t: "A palavra " }, { t: "desembestada", b: 1 }, { t: " quer dizer:" }],
        ],
        alt: ["Muito rápida e sem controle.", "Parada no meio do caminho.", "Andando bem devagar."],
        certa: "A",
        desc: "D022_P",
        hab: "Inferir o sentido de palavra ou expressão pelo contexto.",
      },
    ],
  },
  {
    n: 6,
    titulo: "Semente",
    imagem: "Corte do solo: a semente enterrada, as raízes descendo e um broto saindo para fora da terra.",
    versos: [
      "Uma semente é um segredo",
      "guardado dentro do escuro:",
      "não tem pressa, não tem medo,",
      "só tem plano para o futuro.",
      "",
      "Debaixo da terra fria",
      "ela espera, recolhida,",
      "até que a chuva, um belo dia,",
      "bata na porta da vida.",
      "",
      "Depois vem o verde, vem o galho,",
      "vem a sombra, vem o ninho.",
      "Toda árvore, no começo,",
      "foi um ponto no caminho.",
    ],
    perguntas: [
      {
        n: 16,
        pista: "Leia o verso 1.",
        imagem: "Corte do solo com a semente enterrada. Dentro da semente, um cofrinho fechado ou um envelope lacrado, mostrando que ela guarda algo escondido. Etiqueta: “verso 1 — uma semente é um segredo”.",
        enunciado: [
          [{ t: "No verso 1, o poeta diz que a semente " }, { t: "É", b: 1 }, { t: " um segredo." }],
          [{ t: "Ele não usou a palavra “como”." }],
          [{ t: "Como se chama esse recurso?" }],
        ],
        alt: ["Comparação.", "Metáfora.", "Onomatopeia."],
        certa: "B",
        desc: "D043_P",
        hab: "Reconhecer recursos estilísticos na construção do texto.",
      },
      {
        n: 17,
        pista: "Leia os versos 5 e 6.",
        imagem: "A semente bem pequena e encolhida, guardadinha debaixo da terra fria, esperando quietinha. Etiqueta: “verso 6 — ela espera, recolhida”.",
        enunciado: [
          [{ t: "A semente espera " }, { t: "recolhida", b: 1 }, { t: " debaixo da terra." }],
          [{ t: "A palavra " }, { t: "recolhida", b: 1 }, { t: " quer dizer:" }],
        ],
        alt: ["Espalhada pelo chão.", "Guardada e encolhida.", "Exposta ao sol."],
        certa: "B",
        desc: "D022_P",
        hab: "Inferir o sentido de palavra ou expressão pelo contexto.",
      },
      {
        n: 18,
        pista: "Leia os versos 7 e 8.",
        imagem: "A chuva chegando e batendo numa portinha desenhada na terra. Do outro lado da porta, a semente começando a virar broto. Etiqueta: “verso 8 — bata na porta da vida”.",
        enunciado: [
          [{ t: "A chuva chega e “" }, { t: "bata na porta da vida", b: 1 }, { t: "”." }],
          [{ t: "Essa frase quer dizer que:" }],
        ],
        alt: ["A chuva vai destruir a semente.", "Chegou a hora de a semente nascer.", "A chuva foi embora do lugar."],
        certa: "B",
        desc: "D022_P",
        hab: "Inferir o sentido de palavra ou expressão pelo contexto.",
      },
    ],
  },
  {
    n: 7,
    titulo: "A lua e o poste",
    imagem: "Uma esquina à noite: o poste aceso jogando luz no chão e, no céu, a lua cheia.",
    versos: [
      "Na esquina, o poste acende",
      "sua luz de todo dia.",
      "Lá em cima, sem fazer conta,",
      "a lua também acendia.",
      "",
      "O poste, muito orgulhoso,",
      "disse: — Sou eu quem clareia!",
      "A lua não respondeu:",
      "seguiu prateando a areia.",
    ],
    perguntas: [
      {
        n: 19,
        pista: "Leia os versos 5 e 6.",
        imagem: "O poste da esquina em pose orgulhosa, peito estufado, com um balão de fala escrito “Sou eu quem clareia!”. A lua aparece calada lá em cima. Etiqueta: “verso 6”.",
        enunciado: [
          [{ t: "No poema, o poste fica " }, { t: "orgulhoso", b: 1 }, { t: " e " }, { t: "fala", b: 1 }, { t: "." }],
          [{ t: "Mas o poste é um objeto." }],
          [{ t: "Como se chama esse recurso?" }],
        ],
        alt: ["Personificação.", "Hipérbole.", "Aliteração."],
        certa: "A",
        desc: "D043_P",
        hab: "Reconhecer recursos estilísticos na construção do texto.",
      },
      {
        n: 20,
        pista: "Leia o verso 8.",
        imagem: "A lua cheia jogando sua luz na areia. A areia fica com um brilho prateado, como se estivesse pintada de prata pela luz. Etiqueta: “verso 8 — seguiu prateando a areia”.",
        enunciado: [
          [{ t: "A lua “seguiu " }, { t: "prateando", b: 1 }, { t: " a areia”." }],
          [{ t: "Essa frase quer dizer que a lua:" }],
        ],
        alt: ["Cobriu a areia de prata de verdade.", "Deixou a areia com brilho de prata.", "Varreu a areia da esquina."],
        certa: "B",
        desc: "D022_P",
        hab: "Inferir o sentido de palavra ou expressão pelo contexto.",
      },
    ],
  },
];

const RECURSOS = [
  ["RIMA", "Duas palavras terminam com o mesmo som.", "telhado / prateado", "Duas palavras ligadas por um risco, com a terminação igual destacada."],
  ["REPETIÇÃO", "A mesma palavra aparece várias vezes seguidas.", "roda, roda, roda", "A mesma palavra escrita três vezes, uma atrás da outra."],
  ["ONOMATOPEIA", "A palavra imita um som de verdade.", "tic-tac / tec, tec", "Um sino ou relógio com a letra do som saindo dele."],
  ["PERSONIFICAÇÃO", "Uma coisa ou um animal faz algo que só gente faz.", "“a chuva senta no chão”", "Uma gota de chuva sentada, com rostinho."],
  ["COMPARAÇÃO", "Aproxima duas coisas usando a palavra “como”.", "“some como quem passeia”", "Duas figuras lado a lado com a palavra COMO entre elas."],
  ["METÁFORA", "Diz que uma coisa É outra, sem usar a palavra “como”.", "“a semente é um segredo”", "Uma semente com um sinal de igual e um cofrinho fechado."],
  ["ALITERAÇÃO", "O mesmo som se repete em palavras próximas.", "“mar manso murmura”", "Três ondas, cada uma com um M grande em cima."],
  ["HIPÉRBOLE", "Um exagero feito de propósito.", "“mil braços de poeira”", "Um vento com braços demais, exagerado."],
  ["ANTÍTESE", "Duas ideias contrárias colocadas juntas.", "seco / verde", "Imagem dividida: metade terra rachada, metade quintal verde."],
];

module.exports = { PARTES, RECURSOS };
